//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAddressManageTool.Core.Message.Implement {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessageMapping {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageMapping() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyAddressManageTool.Core.Message.Implement.ErrorMessageMapping", typeof(ErrorMessageMapping).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   M0001 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EA0001 {
            get {
                return ResourceManager.GetString("EA0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0009 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EA0002 {
            get {
                return ResourceManager.GetString("EA0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0010 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EA0003 {
            get {
                return ResourceManager.GetString("EA0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0002 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ES0001 {
            get {
                return ResourceManager.GetString("ES0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0003 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ES0002 {
            get {
                return ResourceManager.GetString("ES0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0007 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ES0003 {
            get {
                return ResourceManager.GetString("ES0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0004 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EV0001 {
            get {
                return ResourceManager.GetString("EV0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0005 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EV0002 {
            get {
                return ResourceManager.GetString("EV0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0006 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EV0003 {
            get {
                return ResourceManager.GetString("EV0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M0008 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EV0004 {
            get {
                return ResourceManager.GetString("EV0004", resourceCulture);
            }
        }
    }
}
