//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAddressManageTool.Core.ViewModel.Implement {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VIewItemNameMap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VIewItemNameMap() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyAddressManageTool.Core.ViewModel.Implement.VIewItemNameMap", typeof(VIewItemNameMap).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   住所１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_Address1 {
            get {
                return ResourceManager.GetString("V0001-Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_Address2 {
            get {
                return ResourceManager.GetString("V0001-Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号（上3桁） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_AddressNumber1 {
            get {
                return ResourceManager.GetString("V0001-AddressNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   郵便番号（下5桁） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_AddressNumber2 {
            get {
                return ResourceManager.GetString("V0001-AddressNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   姓 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_FamilyName {
            get {
                return ResourceManager.GetString("V0001-FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホスト名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_HostName {
            get {
                return ResourceManager.GetString("V0001-HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_Name {
            get {
                return ResourceManager.GetString("V0001-Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メモ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_Remarks {
            get {
                return ResourceManager.GetString("V0001-Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連名１ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_SubName1 {
            get {
                return ResourceManager.GetString("V0001-SubName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連名２ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_SubName2 {
            get {
                return ResourceManager.GetString("V0001-SubName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連名３ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_SubName3 {
            get {
                return ResourceManager.GetString("V0001-SubName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連名４ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_SubName4 {
            get {
                return ResourceManager.GetString("V0001-SubName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連名５ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string V0001_SubName5 {
            get {
                return ResourceManager.GetString("V0001-SubName5", resourceCulture);
            }
        }
    }
}
